'use client';

import { useState } from 'react';
import { verifyPath } from './certificate-types';

interface CertificateActionsProps {
  /** Public verification ID of the earned certificate. */
  verificationId: string;
  /** Origin for building an absolute share link; falls back to window at runtime. */
  origin?: string;
}

type Notice = { tone: 'info' | 'ok'; text: string } | null;

/**
 * Earned-certificate actions: Share link (copies the public verify URL) and
 * Download PDF (STUBBED — there is no PDF library wired; PDFs are generated by a
 * server worker into Supabase Storage, PROJECT.md §8.14). The button is present
 * for fidelity but only surfaces a "coming soon" notice. Nothing here mints or
 * verifies — those are server-authoritative.
 */
export function CertificateActions({ verificationId, origin = '' }: CertificateActionsProps) {
  const [notice, setNotice] = useState<Notice>(null);

  const relativeVerify = verifyPath(verificationId);

  async function handleShare() {
    const base = origin || (typeof window !== 'undefined' ? window.location.origin : '');
    const url = `${base}${relativeVerify}`;
    try {
      if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(url);
        setNotice({ tone: 'ok', text: 'Verification link copied' });
        return;
      }
      throw new Error('clipboard unavailable');
    } catch {
      // Graceful fallback — show the link so the user can copy it manually.
      setNotice({ tone: 'info', text: url });
    }
  }

  function handleDownload() {
    // STUB: PDF generation is a server-worker concern (no PDF lib in the app).
    setNotice({ tone: 'info', text: 'PDF generation coming soon' });
  }

  return (
    <div className="cert-actions">
      <div className="cert-actions-row">
        <button type="button" className="btn btn-ghost btn-sm" onClick={handleShare}>
          Share link
        </button>
        <button type="button" className="btn btn-forest btn-sm" onClick={handleDownload}>
          Download PDF
        </button>
      </div>
      {notice && (
        <p
          role="status"
          className={notice.tone === 'ok' ? 'cert-notice cert-notice-ok' : 'cert-notice'}
        >
          {notice.text}
        </p>
      )}
    </div>
  );
}
